export const CRUDTYPE = Object.freeze({
  CREATE_SUCCESS: "create_success",
  CREATE_ERROR: "create_error",
  UPDATE_SUCCESS: "update_success",
  UPDATE_ERROR: "update_error",
  DELETE_SUCCESS: "delete_success",
  DELETE_ERROR: "delete_error",
});

export const CRUDITEM = Object.freeze({
  WORKER: "Worker",
  PROJECT: "Project",
  PROJECT_WORKER: "Project Worker",
  PAYROLL: "Payroll",
  EMPLOYEE_PAYROLL: "Employee Payroll",
  EMPLOYEE_POSITION: "Employee Position",
  EMPLOYEEATTENDANCE: "Employee Attendance",
  CostCenter: "CostCenter",
  ACCOUNT: "Account",
  ADVANCE: "Advance",
  DoneBy: "DoneBy",
  TOOL: "Tool",
  TOOL_ALLOCATION: "Tool Allocation",
  PURCHASE: "Purchase",
  PURCHASE_RETURN: "PurchaseReturn",
  CUSTOMER: "Customer",
  SUPPLIER: "Supplier",
  SALE_RETURN: "SaleReturn",
  ExpenseType: "ExpenseType",
  ITEM: "Item",
  CASH_BOOK: "CashBook",
  PARTNER: "Partner",
  PARTNERSHIP: "Partnership",
  JOBSHEET: "JobSheet",
  DAILY_SUMMARY: "DailySummary",
  MONTHLY_SUMMARY: "MonthlySummary",
  BRAND: "Brand",
  CATEGORY: "Category",
  Unit: "Unit",
  EmployeePosition: "EmployeePosition",
  Role: "Role",
  EMPLOYEE: "Employee",
  MEMBER: "Member",
  MEMBERATTENDANCE: "MemberAttendance",
  MEMBERSHIP_PLAN: "MembershipPlans",
  PAYMENT: "Payment",
  TEMPLATE: "Template",
  ROLE: "Role",
  USER: "User",
  Tenant: "Tenant",
  DONEBY: "Done by",
  COSTCENTER: "Cost Center",
  EXERCISE: "Exercise",
  WORKOUTPLAN: "WorkoutPlan",
  WORKOUTPLANITEM: "WorkoutPlanItem",
  PTBOOKING: "PtBooking",
  PTSESSION: "PtSession",
  PTPACKAGE: "PtPackage",
  SUBSCRIPTION: "Subscription",
  DIET_PLAN: "Diet Plan",
  DIET_PLAN_ITEM: "Diet Plan Item",
  EXPENSE: "Expense",
  CASHBOOK: "Tranasaction",
  BOOKING_TRAVELER: "Bokking Traveler",
  HOTEL: "Hotel",
  INVOICE_ITEM: "Invoice Item",
  INVOICE: "Invoice",
  TOUR_PACKAGE: "Tour Package",
  FINANCE: "Finance",
  FINANCIER: "Financier",
  SALE: "Sale",
  VEHICLE: "Vehicle",
  SETTINGS: "Settings",
  BROKER: "Broker",
  BROKERAGE: "Brokerage",
  ATTENDANCE: "Attendance",
  STAFF: "Staff",
  TENANT: "Tenant",
  EXPENSETYPE: "ExpenseType",

  FlightTicket: "Flight Ticket",
  Visa: "Visa",
  ServiceType: "Service Type",
  Service: "Service",
  BOOKING: "Booking",

  TRANSPORT: "Transport",
  Airline: "Airline",
  Sector: "Sector",
  PRESCRIPTION: "Prescription",
});
