export const CRUDTYPE = Object.freeze({
  CREATE_SUCCESS: "create_success",
  CREATE_ERROR: "create_error",
  UPDATE_SUCCESS: "update_success",
  UPDATE_ERROR: "update_error",
  DELETE_SUCCESS: "delete_success",
  DELETE_ERROR: "delete_error",
});

export const CRUDITEM = Object.freeze({
  SALE: "Sale",
  PURCHASE: "Purchase",
  PURCHASE_RETURN: "PurchaseReturn",
  EXPENSE: "Expense",
  CUSTOMER: "Customer",
  SUPPLIER: "Supplier",
  SALE_RETURN: "SaleReturn",
  ExpenseType: "ExpenseType",
  ITEM: "Item",
  ACCOUNT: "Account",
  CASH_BOOK: "CashBook",
  PARTNER: "Partner",
  PARTNERSHIP: "Partnership",
  JOBSHEET: "JobSheet",
  JOBSHEET: "Jobsheet",
  DAILY_SUMMARY: "DailySummary",
  MONTHLY_SUMMARY: "MonthlySummary",
  BRAND: "Brand",
  CATEGORY: "Category",
  DoneBy: "DoneBy",
  CostCenter: "CostCenter",
  Unit: "Unit",
  EMPLOYEE: "Employee",
  EmployeePosition: "EmployeePosition",
  Role: "Role",
});
