export const ExtraFields = Object.freeze({
  Date: "Date",
  Customer: "Customer",
  Supplier: "Supplier",
  InvoiceNo: "Invoice No",
  Status: "Status",
  Account: "Account",
  TotalAmount: "Total Amount",
  PaidAmount: "Paid Amount",
  Balance: "Balance",
  DoneBy: "Done By",
  CostCenter: "Cost Center",
  Item: "Item",
  Quantity: "Quantity",
  Amount: "Amount",
  Reason: "Reason",
  Discount: "Discount",
  RefundAmount: "Refund Amount",
  Type: "Type",
  Ledger: "Ledger",
  Description: "Description",
  Paid: "Paid",
  ItemName: "Item Name",
  Servicer: "Servicer",
  Charges: "Charges",
  Cost: "Cost",
  Profit: "Profit",
  BarCode: "Bar Code",
  VoucherNo: "Voucher No",
  InvoiceType: "Invoice Type",
  PaymentFrom: "Payment From",
  PaymentTo: "Payment To",
  Name: "Name",
  Category: "Category",
  SKU: "SKU",
  Brand: "Brand",
  Unit: "Unit",
  Barcode: "Barcode",
  Stock: "Stock",
  Price: "Price",
  PriceWTax: "Price W/ Tax",
  Tax: "Tax",
  Address: "Address",
  Phone: "Phone",
  Email: "Email",
  CreditLimit: "Credit Limit",
  OutstandingBalance: "Outstanding Balance",
  PaymentTerms: "Payment Terms",
  ReturnDate: "Return Date",
  OrderDate: "Order Date",
  DeliveryDate: "Delivery Date",
  ActualDate: "Actual Date",
  OrderStatus: "Order Status",
});