import VisaReport from "../../apps/travelx/pages/Reports/VisaReport/component";

export const Report = Object.freeze({
  EXPENSE: "Expense",
  CashBook: "Transaction",
  EXPENSE_TYPE: "Expense Type",
  ACCOUNT: "Account",
  Ledger: "Ledger",

  WORKER: "Worker",
  PROJECT: "Project",
  ProjectWorker: "Project Worker",
  Tasks: "Tasks",
  TaskProgress: "Task Progress",
  ATTENDANCE: "Attendance",
  PAYROLL: "Payroll",
  EstimateItems: "Estimate Items",
  Materials: "Materials",
  EstimateMaterials: "Estimate Materials",
  Employee: "Employee",
  EmployeePosition: "EmployeePosition",
  Tools: "Tools",
  ToolAllocations: "Tool Allocations",
  Advances: "Advances",
  Vendors: "Vendors",
  ExpenseType: "ExpenseType",
  Expense: "Expense",
  CostCenter: "Cost Center",
  Advance: "Advance",
  DoneBy: "DoneBy",
  Estimates: "Estimates",
  TOOL: "Tool",
  TOOL_ALLOCATION: "Tool Allocation",

  Purchase: "Purchase",
  SaleReturn: "SaleReturn",
  Supplier: "Suppliers",
  Customer: "Customer",
  Item: "Item",
  Partner: "Partner",
  Partnership: "Partnership",
  Jobsheet: "JobSheet",
  Brand: "Brand",
  Category: "Category",
  Accounts: "Accounts",
  Unit: "Unit",
  RolePermissions: "Permissions",
  Role: "Role",

  Member: "Member",
  MemberAttendance: "Member attendance",
  MEMBERSHIP_PLAN: "Membership plans",
  Subscription: "Subscription",
  User: "User",
  DONEBY: "Done by",
  COSTCENTER: "Cost Center",
  Exercise: "Exercise",
  WorkoutPlan: "Workout Plan",
  WorkoutPlanItem: "Workout Plan Item",
  ClassList: "Class List",
  ClassSchedule: "Class Schedule",
  ClassBooking: "Class Booking",
  PtBooking: "PT Booking",
  PtSession: "PT Session",
  PtPackage: "PT Package",
  Account: "Account",
  DietPlanItem: "Diet Plan Item",
  DietPlan: "Diet Plan",
  EMPLOYEEATTENDANCE: "Employee Attendance",
  EmployeePayroll: "Employee Payroll",
  LeadMember: "Lead Member",
  BOOKING: "Booking",
  BOOKING_TRAVELER: "Booking Traveler",
  HOTEL: "Hotel",
  INVOICE_ITEM: "Invoice Item",
  INVOICE: "Invoice",
  TOUR_PACKAGE: "Tour Package",

  Sale: "Sale",
  Vehicle: "Vehicle",

  Broker: "Broker",
  Brokerage: "Brokerage",
  Financier: "Financier",
  Finance: "Finance",
  Brocker: "Brocker",
  Staff: "Staff",
  Challan: "Challan",
  VehicleEnquiry: "Vehicle Enquiry",
  Invoice: "Invoice",
  InvoiceTemplate: "InvoiceTemplate",
  FlightTicket: "Flight Ticket",
  FlightTicketReturn: "Flight Ticket Return",
  Visa: "Visa",
  VisaReport: "Visa Report",
  ServiceType: "Service Type",
  Service: "Service",
  ServiceReturn: "Service Return",
  Payment: "Payment",
  PaymentList: "Payment List",
  Transport: "Transport",
  Receipt: "Receipt",
  Airline: "Airline",
  Sector: "Sector",
});
