export const Transaction = Object.freeze({
  EXPENSE: "Expense",
  ACCOUNT: "Account",
  EXPENSE_TYPE: "ExpenseType",

  WORKER: "Worker",
  PAYROLL: "Payroll",
  Sale: "Sale",
  Purchase: "Purchase",
  Expense: "Expense",
  Employee: "Employee",
  Supplier: "Supplier",
  Customer: "Customer",
  Account: "Account",
  ExpenseType: "ExpenseType",
  Item: "Item",
  Partner: "Partner",
  Jobsheet: "JobSheet",
  SaleReturn: "SaleReturn",
  EmployeePosition: "EmployeePosition",
  Role: "Role",
  MEMBER: "Member",
  MEMBERATTENDANCE: "MemberAttendance",
  MEMBERSHIP_PLAN: "MembershipPlans",
  SUBSCRIPTION: "Subscription",
  User: "User",
  DONEBY: "Done by",
  COSTCENTER: "Cost Center",
  PTSESSION: "PtSession",
  PTBOOKING: "PtBooking",
  PTPACKAGE: "PtPackage",
  EXERCISE: "Exercise",
  WORKOUTPLAN: "WorkoutPlan",
  WORKOUTPLANITEM: "WorkoutPlanItem",
  SUBSCRIPTIONFREEZE: "Subscription Freeze",
  BOOKING: "Bokking",
  Advance: "Advance",
  Finance: "Finance",
  Vehicle: "Vehicle",
  Broker: "Broker",
  Financier: "Financier",
  Partnership: "Partnership",
  Brokerage: "Brokerage",
  Invoice: "Invoice",
  INVOICE_TEMPLATES: "InvoiceTemplate",
});
